/*
    Action types:
 */
const actionTypes = {
    FETCH_PLACES_STARTED: 'FETCH_PLACES_STARTED',
    FETCH_PLACES_SUCCEEDED: 'FETCH_PLACES_SUCCEEDED',
    FETCH_PLACES_FAILED: 'FETCH_PLACES_FAILED',
    TOGGLE_LIST_VISIBILITY: 'TOGGLE_LIST_VISIBILITY',
    CLEAR_QUERY: 'CLEAR_QUERY',
    SEARCH_PLACE: 'SEARCH_PLACE',
    LOAD_MAP_FAILED: 'LOAD_MAP_FAILED',
    LOAD_MAP_SUCCEEDED: 'LOAD_MAP_SUCCEEDED',
    ERROR_CAUGHT: 'ERROR_CAUGHT',
    ERROR_CLEAR: 'ERROR_CLEAR'
}

export default actionTypes;