/*
    Action types:
 */

const actionTypes = {
    FETCH_PLACES_STARTED: 'FETCH_PLACES_STARTED',
    FETCH_PLACES_FINISHED: 'FETCH_PLACES_FINISHED',
    FETCH_PLACES_FAILED: 'FETCH_PLACES_FAILED',
    SELECT_PLACE: 'SELECT_PLACE',
    TOGGLE_LIST_VISIBILITY: 'TOGGLE_LIST_VISIBILITY',
    CLEAR_QUERY: 'CLEAR_QUERY',
    SEARCH_PLACE: 'SEARCH_PLACE',
    LOAD_MAP_FAILED: 'LOAD_MAP_FAILED'
}

export default actionTypes;